@echo off
echo Starting GoodbyeDPI test...
cd /d "d:\FilesHan\kod\GUI\last\GoodbyeDPI_GUI\src\64_exe"
goodbyedpi_new.exe -4 --dns-addr 77.88.8.8 --dns-port 1253 --dnsv6-addr 2a02:6b8::feed:0ff --dnsv6-port 1253
echo Program finished. Press any key to close...
pause
